sudo: false
addons:
  apt:
    packages:
      - build-essential
      - ikiwiki
      - libtext-multimarkdown-perl
      - libimage-magick-perl
      - cpanminus
install:
  - openssl aes-256-cbc -K $encrypted_4f43c47a058e_key -iv $encrypted_4f43c47a058e_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config --global push.default simple
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from
    `git log -n 1 --format='commit %h - %s'`"
script:
  #- set -e
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm -n YAML::Any YAML::XS Sort::Naturally
  - export PERL5LIB="$PERL5LIB:./.ikiwiki-plugin:./rubykat-ikiplugins"
  - ikiwiki --rebuild --setup project-renard.setup --url 'http://project-renard.github.io/'
  - git clone --bare -b master git@github.com:project-renard/project-renard.github.io.git _site/.git
  - cd _site
  - git config core.bare false
  - git add -f .
  - 'git commit -m "${COMMIT_MESSAGE}" || true'
  - git push -f git@github.com:project-renard/project-renard.github.io.git master:master

branches:
  only:
    - source
