#sudo: false
sudo: required
addons:
  apt:
    packages:
      - build-essential
      - ikiwiki
install:
  - sudo apt-get install ikiwiki
  - openssl aes-256-cbc -K $encrypted_4f43c47a058e_key -iv $encrypted_4f43c47a058e_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from
    `git log -n 1 --format='commit %h - %s'`"
script:
  #- set -e
  - export PERL5LIB="./.ikiwiki-plugin"
  - ikiwiki --rebuild --setup project-renard-design.setup --url 'http://project-renard.github.io/design/'
  - git clone --bare -b gh-pages git@github.com:project-renard/design.git _site/.git
  - cd _site
  - git config core.bare false
  - git add -f .
  - 'git commit -m "${COMMIT_MESSAGE}"'
  - git push -f git@github.com:project-renard/design.git gh-pages:gh-pages

branches:
  only:
    - master
